name: Flask CI Pipeline

on: push

jobs:
  flask-ci-job:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-flask-app .

      - name: Run Docker container & Smoke test
        run: |
          docker run -d -p 5000:5000 --name my-flask-container my-flask-app
          sleep 5
          curl http://localhost:5000

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUBUSERNAME }}" --password-stdin

      - name: Tag and Push to Docker Hub
        run: |
          docker tag my-flask-app ${{ secrets.DOCKERHUBUSERNAME }}/my-flask-app:latest
          docker push ${{ secrets.DOCKERHUBUSERNAME }}/my-flask-app:latest